# Install pre-commit hooks via
# pre-commit install

repos:
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
    - repo: https://github.com/adamchainz/blacken-docs
      rev: 1.19.1
      hooks:
          - id: blacken-docs
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            files: \.(html|md|yml|yaml)
            args: [--prose-wrap=preserve]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.3
      hooks:
          - id: ruff
            args:
                - --fix
