# Install pre-commit hooks via
# pre-commit install

repos:
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
    - repo: https://github.com/adamchainz/blacken-docs
      rev: 1.13.0
      hooks:
          - id: blacken-docs
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.9-for-vscode
      hooks:
          - id: prettier
            files: \.(html|md|yml|yaml)
            args: [--prose-wrap=preserve]
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.272
      hooks:
          - id: ruff
            args:
                - --fix
