name: Basic CI

on: [pull_request, workflow_dispatch]

jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: run python script
              run: |
                  pip install -r requirements/dev.txt
                  pip install -r requirements/docs.txt
                  pip install -r requirements/default.txt
